Repository Lakhankumawat/smart-home-app, pull requests merged in 2022-04, with the labels that each got.

#50 fixed overflow on energy saving card
  lib/src/screens/home_screen/components/savings_container.dart
Labels: enhancement, design, develop, next-review-needed, proposal

#45 Added Menu Page
  assets/icons/menu_icons/devices.svg
  assets/icons/menu_icons/faq.svg
  assets/icons/menu_icons/notifications.svg
  assets/icons/menu_icons/settings.svg
  assets/icons/menu_icons/stats.svg
  lib/src/screens/home_screen/home_screen.dart
  lib/src/screens/menu_page/components/body.dart
  lib/src/screens/menu_page/components/list_tile.dart
  lib/src/screens/menu_page/components/menu_list.dart
  lib/src/screens/menu_page/menu_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, design, develop, next-review-needed, Assigned, changes-pending

#40 Set event screen
  assets/fonts/ABeeZee-Italic.ttf
  assets/fonts/ABeeZee-Regular.ttf
  lib/main.dart
  lib/routes/routes.dart
  lib/src/screens/edit_profile/components/image_picker.dart
  lib/src/screens/home_screen/components/body.dart
  lib/src/screens/set_event_screen/components.dart
  lib/src/screens/set_event_screen/components/add_event_dialog.dart
  lib/src/screens/set_event_screen/components/calendar_theme.dart
  lib/src/screens/set_event_screen/components/event.dart
  lib/src/screens/set_event_screen/components/event_list_tile.dart
  lib/src/screens/set_event_screen/components/select_day_dialog.dart
  lib/src/screens/set_event_screen/components/set_event_screen_theme.dart
  lib/src/screens/set_event_screen/set_event_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, design, develop, Assigned, changes-pending

#58 fixed smart fan screen overflow
  lib/src/screens/smart_fan/components/body.dart
  pubspec.lock
Labels: enhancement, design, develop, next-review-needed, Assigned

#62 Stats screen
  android/app/src/main/res/drawable-hdpi/splash.png
  android/app/src/main/res/drawable-mdpi/splash.png
  android/app/src/main/res/drawable-xhdpi/splash.png
  android/app/src/main/res/drawable-xxhdpi/splash.png
  android/app/src/main/res/drawable-xxxhdpi/splash.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png
  lib/routes/routes.dart
  lib/src/screens/menu_page/components/list_tile.dart
  lib/src/screens/menu_page/components/menu_list.dart
  lib/src/screens/stats_screen/components.dart
  lib/src/screens/stats_screen/components/consumption.dart
  lib/src/screens/stats_screen/components/stats_bottom_app_bar.dart
  lib/src/screens/stats_screen/components/stats_chart.dart
  lib/src/screens/stats_screen/components/stats_device_consumption_chart.dart
  lib/src/screens/stats_screen/components/stats_electricity_usage_chart.dart
  lib/src/screens/stats_screen/components/type_selection.dart
  lib/src/screens/stats_screen/stats_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, design, develop, GSSoC22, next-review-needed, proposal, Assigned

#52 #6 about page
  assets/fonts/Lexend-VariableFont_wght.ttf
  assets/icons/svg/chat.svg
  assets/icons/svg/heart.svg
  assets/icons/svg/help.svg
  assets/icons/svg/info.svg
  assets/icons/svg/profile.svg
  assets/icons/svg/star.svg
  assets/icons/svg/team.svg
  lib/main.dart
  lib/src/screens/about_screen/about_us_screen.dart
Labels: enhancement, design, develop, next-review-needed, proposal, changes-pending

#66 Added Smart TV Screen
  assets/images/tv.png
  lib/provider/getit.dart
  lib/routes/routes.dart
  lib/src/screens/home_screen/components/body.dart
  lib/src/screens/smart_tv/components/body.dart
  lib/src/screens/smart_tv/components/expandable_bottom_sheet.dart
  lib/src/screens/smart_tv/components/intensity_slider.dart
  lib/src/screens/smart_tv/components/mood_toggle_buttons.dart
  lib/src/screens/smart_tv/smart_tv.dart
  lib/view/smart_tv_view_model.dart
Labels: enhancement, design, develop, next-review-needed, proposal
