Repository Lakhankumawat/smart-home-app, pull requests merged in 2022-05, with the labels that each got.

#73 Fix menupage
  lib/src/screens/menu_page/components/body.dart
  lib/src/screens/savings_screen/components/savings_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, next-review-needed, proposal

#80 added favourites screens
  android/app/src/main/res/drawable-hdpi/splash.png
  android/app/src/main/res/drawable-mdpi/splash.png
  android/app/src/main/res/drawable-xhdpi/splash.png
  android/app/src/main/res/drawable-xxhdpi/splash.png
  android/app/src/main/res/drawable-xxxhdpi/splash.png
  assets/images/favourite.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png
  lib/src/screens/favourites_screen/components/body.dart
  lib/src/screens/favourites_screen/components/favourite_tile.dart
  lib/src/screens/favourites_screen/components/favourites_list.dart
  lib/src/screens/favourites_screen/favourites_screen.dart
  lib/src/screens/home_screen/components/body.dart
  lib/src/screens/home_screen/components/dark_container.dart
  lib/src/screens/home_screen/home_screen.dart
  lib/view/home_screen_view_model.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, question, design, develop, next-review-needed, proposal

#81 IoT For ESP8266 with Firebase
  sketch_may18a.ino
Labels: enhancement, Level2, design, develop, GSSoC22, Approved
