Repository Lakhankumawat/smart-home-app, pull requests merged in 2022-03, with the labels that each got.

#18 smart fan screen made
  android/app/src/main/res/drawable-hdpi/splash.png
  android/app/src/main/res/drawable-mdpi/splash.png
  android/app/src/main/res/drawable-v21/background.png
  android/app/src/main/res/drawable-xhdpi/splash.png
  android/app/src/main/res/drawable-xxhdpi/splash.png
  android/app/src/main/res/drawable-xxxhdpi/splash.png
  android/app/src/main/res/drawable/background.png
  assets/Lottie/fan.json
  assets/images/fan.png
  ios/Runner/Assets.xcassets/BrandingImage.imageset/Contents.json
  ios/Runner/Assets.xcassets/LaunchBackground.imageset/Contents.json
  ios/Runner/Assets.xcassets/LaunchBackground.imageset/background.png
  lib/provider/getit.dart
  lib/routes/routes.dart
  lib/src/screens/home_screen/components/body.dart
  lib/src/screens/smart_fan/components/body.dart
  lib/src/screens/smart_fan/components/expandable_bottom_sheet.dart
  lib/src/screens/smart_fan/smart_fan.dart
  lib/view/smart_fan_view_model.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, Level3, design, develop, next-review-needed

#30 schedule in lightening screen widget overflow #29
  lib/src/screens/smart_light/components/expandable_bottom_sheet.dart
  lib/src/screens/smart_light/smart_light.dart
  pubspec.lock
Labels: enhancement, design, develop

#33 Edit profile
  lib/routes/routes.dart
  lib/src/screens/edit_profile/components/body.dart
  lib/src/screens/edit_profile/components/image_picker.dart
  lib/src/screens/edit_profile/edit_profile.dart
  lib/src/screens/home_screen/home_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, design, develop, next-review-needed
